# Generated by Django 3.0.3 on 2020-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_title', models.CharField(max_length=200)),
                ('tut_content', models.TextField()),
                ('tut_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
