# Generated by Django 3.0.3 on 2020-02-24 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tut',
            name='tut_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 15, 29, 14, 26541), verbose_name='date published'),
        ),
    ]
