# Generated by Django 3.0.3 on 2020-02-26 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200226_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tut',
            name='tut_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 15, 56, 51, 650518), verbose_name='date published'),
        ),
    ]
