# Generated by Django 3.0.3 on 2020-02-26 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200226_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tut',
            name='tut_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 16, 44, 3, 77749), verbose_name='date published'),
        ),
    ]
